### ISSUE TITLE
Split spring server packages into schema generator and graphql schema runtime

### ISSUE THREAD

**Issue by magaton** [ExpediaGroup/graphql-kotlin#1129]
**Library Version**
4.0.1

**Describe the bug**
```
graphql:
   packages
   
```
is currently mandatory.

**To Reproduce**
if you do not specify
```
graphql:
   packages
   
```
in application.yml (I am using spring boot with graphql-kotlin-spring-server as a dependency
app won't start with an exception:

```
Failed to bind properties under 'graphql' to com.expediagroup.graphql.server.spring.GraphQLConfigurationProperties:

    Reason: Parameter specified as non-null is null: method com.expediagroup.graphql.server.spring.GraphQLConfigurationProperties.<init>, parameter packages

```

**Expected behavior**
this configuration should not be mandatory because library can be used with empty setting.
I am using schema defined in schema.graphql, not in kotlin.

**Comment by smyrick** [comment]
The config is required because if you are using `graphql-kotlin-schema-generator` we need to use reflection to scan the packages to know where your schema classes are. Today `graphql-kotlin-spring-server` depends on the schema generator so the config is required.

What you are asking for is to possibly have the Spring schema generator configuration split out from a more generic Spring GraphQL library that only requires a `GraphQLSchema` object, no matter how it's built. I have been thinking about this as well and it could be an feature enhancement we add to create this new middle configuration module

**Comment by smyrick** [comment]
This work will probably come up when we look into adopting [spring-graphql](https://github.com/spring-projects/spring-graphql) as we will need to generate the `GraphQL` object with our schema generator but then hopefully spring will handle everything else

**Comment by smyrick** [comment]
However in that case we will still need the packages configuration. @magaton I recommend you look at https://github.com/spring-projects/spring-graphql for adopting a generic spring server
