### ISSUE TITLE
More verbose client generation exceptions

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#1173]
**Is your feature request related to a problem? Please describe.**
When generating a client using the plugins, I will sometimes get valid exceptions in my query files. This are most often related to the polymorphic exceptions.

https://github.com/ExpediaGroup/graphql-kotlin/blob/245b4579103e5a20ea9f4d770786aad8e9c92eb1/plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateInterfaceTypeSpec.kt#L124

https://github.com/ExpediaGroup/graphql-kotlin/blob/245b4579103e5a20ea9f4d770786aad8e9c92eb1/plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateInterfaceTypeSpec.kt#L132

The issue is that from just the log alone it is hard to tell where exactly the issue is coming from if I have many query files, fragments, and/or usages of the type.

**Describe the solution you'd like**
The exception should include the file name of the operation that caused the exception, and maybe even the line number if possible

**Comment by dariuszkuc** [comment]
We probably should include operation name in all thrown exceptions.

As for the line numbers -> that info won't be available as query was already parsed and validated, those polymorphic exceptions are thrown because of the explicit client requirements to include `__typename` (so we can correctly deserialize it) and have an exhaustive list of all types (so we don't end up with empty/partial type).
