### ISSUE TITLE
Gradle plugin 5.1.0 breaks GitHub schema generation

### ISSUE THREAD

**Issue by sschuberth** [ExpediaGroup/graphql-kotlin#1303]
**Library Version**

Gradle plugin (and library version) 5.1.0

**Describe the bug**

Upgrading the Gradle pluging from version 5.0.0 to version 5.1.0 starts throwing the following error at build time:

```
* What went wrong:
Execution failed for task ':clients:github-graphql:graphqlGenerateClient'.
> There was a failure while executing work items
   > A failure occurred while executing com.expediagroup.graphql.plugin.gradle.actions.GenerateClientAction
      > Invalid Syntax : More than 15000 parse tokens have been presented. To prevent Denial Of Service attacks, parsing has been cancelled. offending token ':' at line 14335 column 15
```

**To Reproduce**

- Schema Configuration
  - https://github.com/octokit/graphql-schema/blob/master/schema.graphql (official GitHub schema)
- Kotlin code used to generate the schema
  - Checkout https://github.com/oss-review-toolkit/ort/tree/graphql-issue and run e.g. `./gradlew :cli:run --args="--version"`

**Expected behavior**

Code for the schema should be successfully generated just like with version 5.0.0.

**Comment by dariuszkuc** [comment]
Hello 👋 
Thanks for raising this. Underlying issue is caused from a change in GraphQL Java 17.3 (https://github.com/graphql-java/graphql-java/releases/tag/v17.3) and impacts both server (at runtime) and client code (at code generation). Options to make this configurable were added in a commit AFTER the 17.3 was cut but sadly new version was not yet released. In the meantime we might need to do downgrade version of `graphql-java`.

**Comment by sschuberth** [comment]
@dariuszkuc I just saw this coming back with `graphql-kotlin` version 6.2.1. That version depends on `graphql-java` 19.1 which *does* allow to configure the `maxTokens` in `ParserOptions`, but I do not see that option being exposed by the Gradle plugin. Am I missing something?

**Comment by dariuszkuc** [comment]
👋 I opened up a new issue to track it.
