### ISSUE TITLE
server-examples: add a unit test that generates schema.graphql

### ISSUE THREAD

**Issue by jmfayard** [ExpediaGroup/graphql-kotlin#1352]
**Is your feature request related to a problem? Please describe.**

Having the generated GraphQL schema inside the repository and thus part of the pull-review process is very handy.

**Describe the solution you'd like**

In my (private) project, one thing I've done is to add a unit test that
- update a file `schema.graphql` if I'm on my local machine
- fails on the CI if that file is not up-to-date

**Describe alternatives you've considered**

**Additional context**

Related: I added a `/sdl` endpoint for ktor https://github.com/ExpediaGroup/graphql-kotlin/pull/1351
Handy for iterating on the schema, but doesn't allow to follow how the schema evolves in the pull request.

**Comment by dariuszkuc** [comment]
👋 Since code is the source of truth for the schema, IMHO schema file should be a build artifact and not really part of the source code. You would then use that artifact with a schema registry (e.g. [Apollo](https://www.apollographql.com/docs/studio/) and [Hive](https://www.the-guild.dev/blog/graphql-hive-preview)) in your CI/CD pipeline that would allow you to detect schema breaking changes (i.e. while removing a field is a breaking change, if no one is using it it is a safe change to make).

You can generate SDL at build time using one of our plugins -> [Gradle](https://opensource.expediagroup.com/graphql-kotlin/docs/plugins/gradle-plugin-usage#generating-sdl-example) and [Maven](https://opensource.expediagroup.com/graphql-kotlin/docs/plugins/maven-plugin-usage#generating-sdl-example).

**Comment by jmfayard** [comment]
Thank you for the references, I will keep that in mind if I need them later.

For now, I am happy with having the schema inside the repository.

If someone stumble upon this issue, here is the unit test:

```kotlin
class GenerateGraphQLSchema {
    val schema : GraphQLSchema = TODO()
    val schemaFile = File("schema.graphql").absoluteFile
    val isCI = System.getenv("CI") != null

    @Test
    fun `when the GraphQL change, ensure we update the schema dot sql file, or fail in the CI`() {
        val newSchema = schema.print()

        if (isCI) {
            val existingSchema = schemaFile.readText()
            newSchema shouldBeEqualTo existingSchema
        } else {
            schemaFile.writeText(newSchema)
        }
    }
}
```

`.graphqlconfig`  as of https://graphql-config.com/introduction

```
{
  "name": "GraphQL Schema",
  "schemaPath": "schema.graphql",
}
```

**Comment by dariuszkuc** [comment]
Closing this issue as we generally don't recommend to store build artifact (schema) as part of the source code. Other tooling such as schema+operation registry should be used to help detect backwards incompatible changes.
