### ISSUE TITLE
conflict types of differant package

### ISSUE THREAD

**Issue by donhill** [ExpediaGroup/graphql-kotlin#1396]
I have a standard response that includes a Meta section. I am referencing Meta in 2 types defined below. I am trying to generate a client which works just fine but it seems to generate 2 Meta classes in separate packages. One namespace for each query. In the end I get an error like

`com.expediagroup.graphql.generator.exceptions.ConflictingTypesException: Conflicting class names in schema generation [class com.example.generated.groups.Meta, class com.example.generated.users.Meta`

Any thoughts on the above would be great.

I also am wondering if it's possible to generate the queries by the graphql-kotlin-spring-client without creating separate query.graphql files for each endpoint?

type Meta {
  hint: String!
  responseStatus: String!
}

type UserResponse {
  data: Plans!
  meta: Meta!
}

type GroupResponse {
  data: [Group!]
  meta: Meta!
}

**Comment by dariuszkuc** [comment]
Hello 👋 
Can you provide a git repo with a reproduction of the issue? Exception is from schema generation process so question is what are you trying to do? Sounds like you are trying to generate client code and then use it to stand up a graphql server?

**Comment by donhill** [comment]
Let me put something together. 
We will many microservice which are graph servers and clients, we would like to start generating clients. 
You are correct in that we have generated a client and would like to use that in a different graphdl server. The client is in a diff package but seems the server needs to scan those.

**Comment by donhill** [comment]
Here are the sample apps. One is the server which just uses the generated sdl endpoint and some queries. The second is the client-server where you will see the issue on startup.

https://github.com/donhill/kotlin-graphql-conflicting-class-names

**Comment by donhill** [comment]
@dariuszkuc Well I am new to graphql and I think the queries actually need to live on the client-side, so in my case, the client-server is now doing the generation. This actually makes more sense to me now. Since we want the client to control the response being pulled from the server. Thoughts?

**Comment by donhill** [comment]
closing unless you have something else to add.

**Comment by dariuszkuc** [comment]
Hi 👋 
`schema-generator` uses reflections to generate your schema by traversing your query/mutation objects. Your underlying issue was that you were trying to re-use your client generated code directly as the schema for the second graph. While your first server defines a single type, clients are generated per query. Since your queries were selecting overlapping objects it lead to a conflicting type definition in the second graph (and resulting in the thrown exception).

Your GraphQL servers can retrieve the data from any source (including another GraphQL server) but in the example above your second server would need to define their own type (which is mapped to the data returned from the first server).
