### ISSUE TITLE
Spring Startup: class java.lang.String cannot be cast to class graphql.schema.GraphQLDirective

### ISSUE THREAD

**Issue by mr-w1lde** [ExpediaGroup/graphql-kotlin#1451]
What version are you using?
com.expediagroup:graphql-kotlin-spring-server:5.4.1

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'routerFunctionMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration$EnableWebFluxConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.expediagroup.graphql.server.spring.GraphQLRoutesConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springGraphQLServer' defined in class path resource [com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.class]: Unsatisfied dependency expressed through method 'springGraphQLServer' parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLRequestHandler' defined in class path resource [com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLRequestHandler' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQL' defined in class path resource [com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.class]: Unsatisfied dependency expressed through method 'graphQL' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schema' defined in class path resource [com/expediagroup/graphql/server/spring/NonFederatedSchemaAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'schema' threw exception; nested exception is java.lang.ClassCastException: class java.lang.String cannot be cast to class graphql.schema.GraphQLDirective (java.lang.String is in module java.base of loader 'bootstrap'; graphql.schema.GraphQLDirective is in unnamed module of loader 'app')`

Steps to reproduce the behavior. 
Create a base Spring Application - https://start.spring.io/
Minimal Setup via Tutorial With One Query - https://opensource.expediagroup.com/graphql-kotlin/docs/

Spring Application successful run? What I'm doing wrong? :)

**Comment by dariuszkuc** [comment]
Hello 👋 
Can you provide a link to the repository that reproduces this issue?

**Comment by mr-w1lde** [comment]
Yeah! I can get you a local copy of spring demo projec
funny fact, I've updated graphql version to 6.0.0-alpha4 and the error has gone 

[demo.zip](https://github.com/ExpediaGroup/graphql-kotlin/files/8848341/demo.zip)
t

**Comment by mitsuhealth** [comment]
I was about to come here to report this bug. This is a very serious bug that basically completely breaks graphql-kotlin with Spring Boot 2.7.0. It works with 2.6.8 and below. Not sure if the bug is in Spring Boot or graphql-kotlin but I've tried this with a completely minimal, fresh Spring Boot installation straight out of Initializr and it fails the moment you install the graphql-kotlin package in the latest (5.4.1) version as soon as you start the server. Switch to 2.6.8 (the plugin and all Spring packages) and do a gradle clean; gradle build -x test; gradle bootRun and all is well.

This is a breaking bug. One of my engineers lost hours and hours on this bug, trying to figure out what he was doing wrong - he wasn't doing anything wrong, except using Spring Boot 2.7.0 with graphql-kotlin.

**Comment by dariuszkuc** [comment]
Hello 👋 
The underlying issue is that starting with Spring Boot 2.7.0 they (Spring Boot folks) started to manage `graphql-java` as one of their dependencies (which is used by the newly released `spring-graphql` package). TLDR they depend on `graphql-java` v18.1 whereas `graphql-kotlin` 5.x depends on v17.

Solutions are either to
- use SpringBoot 2.6.x with `graphql-kotlin` 5.x (or simply use `graphql-kotlin-spring-server` which pulls in the appropriate Spring Boot libs)
- use SpringBoot 2.7.x with `graphql-kotlin` 5.x but manually override the `graphql-java` version to v17
- use SpringBoot 2.7.x with `graphql-kotlin` 6.x (final release has pending federation v2 changes)

**Comment by samuelAndalon** [comment]
reopenning to  force graphql java v17 in 5.x.x

**Comment by samuelAndalon** [comment]
https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/5.5.0
