### ISSUE TITLE
Add payload to acknowledgeMessage

### ISSUE THREAD

**Issue by seijihirao** [ExpediaGroup/graphql-kotlin#1685]
# Problem

Hi! I have a `graphql-kotlin-spring-server` running and working with its playground. The problem is when I have a client using `graphql-ws` as it returns an error because [it doesn't expect a null payload](https://github.com/enisdenjo/graphql-ws/commit/b46379e5946b8ce10e907588399350b8ba256c4c#diff-1f963b5ae3613de37b5354a3da594cdef878e0715ad0eb3896bd701e2511b273R232) from ack messages, only undefined or objects.

As I was searching for a solution on the backend I found that [it doesn't have a payload by default](https://github.com/ExpediaGroup/graphql-kotlin/blob/6.x.x/servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandler.kt#L57) and I haven't found a hook to insert a payload.

# What I tried

I tried looking into configurations and hooks but didn't find one that could edit the payloads.
I also tried to override the `subscriptionWebSocketHandler` function, but it's not a conditional bean, so didn't work.

# Question

Is there a way to remove payload field or modify it? Also, as it breaks subscriptions by default shouldn't this payload field be removed by default?

**Comment by dariuszkuc** [comment]
Hello 👋 

You are linking to two different protocols -> when we originally added basic subscription support we implemented it using [apollographql/subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws). Since then Apollo `subscriptions-transport-ws` was deprecated in favor of  `graphql-ws`. While similar, they are different protocols.

I'd recommend to disable the default `graphql-kotlin-spring-server` subscriptions and instead add your own implementation for `graphql-ws`. We are also always open to contributions!

To avoid confusion around this -> @samuelAndalon unsure if lib will be updated to support new protocol anytime soon so in the meantime maybe existing built-in subscription support should be deprecated/removed altogether in future versions?

Thanks,
Derek

**Comment by seijihirao** [comment]
Thanks for the response, I will look into implementing over the default `graphql-kotlin-spring-server`, and I upvote the idea to deprecate the subscriptions till the new protocol is supported. 
Also it looks like the `graphql-ws` repository that I used fixed the non-null necessity.

Thanks!
