### ISSUE TITLE
Directives on Input Types

### ISSUE THREAD

**Issue by de55** [ExpediaGroup/graphql-kotlin#363]
The schema generator will automatically append "Input" to a type that is used, allowing the same class to be used for input types and types.

In the federation project, an error is thrown when an input type has the KeyDirective annotation:
InvalidSchemaDirectiveWiringException: Directive key not applicable on specified WidgetInput GraphQLType, valid directive locations [OBJECT, INTERFACE]

That means that one cannot use the same class for both the Input Type and Type if the Type is a Federation Type.

Is that the intended outcome or should the KeyDirective annotation just be ignored on input types?

**Comment by smyrick** [comment]
Thank you for the issue. It appears this is a valid bug so I will change the label. Since we can't control the annotation location in Kotlin to just be on "input" types I think we need to add logic into the InputTypeBuilder that filters the directives it adds to ones that only have INPUT_TYPE. This is not just an issue with KeyDirective but all directives

**Comment by dariuszkuc** [comment]
Per [GraphQL spec](https://graphql.github.io/graphql-spec/June2018/#sec-Type-System.Directives) directives can be applied on the input object and input field definition. Since we are using same POJOs to generate both input and output types, currently we don't have an option to conditionally specify which directives should be applicable to input and which ones should be applicable to the output. I guess it could be possible to apply directives conditionally based on their valid locations but it would also break our [current validation that ensures you don't accidentally apply directive to an unsupported location](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinDirectiveWiringFactory.kt#L70).

"Simplest" workaround would be to create a separate set of federated POJOs without annotations that would be used for input only.

**Comment by smyrick** [comment]
I see the problem here. It's not just a simple check since this class is still valid until you happen to use it as an argument

```kotlin
@KeyDirective(FieldSet("id"))
class Product(val id: String, val name: String)
```

@dariuszkuc Do we extend the generator to have a hook when adding directive and then we can use this hook in the federation library to ignore specific values?

**Comment by dariuszkuc** [comment]
> @dariuszkuc Do we extend the generator to have a hook when adding directive and then we can use this hook in the federation library to ignore specific values?

We could add a hook that conditionally adds it but that would break our current validation that ensures we don't accidentally apply directives that are not applicable on the target. Neither one of those situations is ideal but I'd lean towards keeping the validation on. IMHO by following a workaround to create separate input and output classes with their own specific directives it would also lead to a clearer data model.

**Comment by dariuszkuc** [comment]
Closing this as `won't fix`. This is a limitation of generating GraphQL output and input types from the same Kotlin object. Workaround is as simple as creating separate objects (they are different objects in GraphQL schema anyway) that has directives applicable to the the input/output type.
