### ISSUE TITLE
Graphql context not set when graphql path has variables

### ISSUE THREAD

**Issue by guillaumeNaimi** [ExpediaGroup/graphql-kotlin#452]
**Library Version**
1.2.2

**Describe the bug**
When we have a graphql path with parameters like `/reporter/api/platform/{platformId}/graphql` the context is not set cause of the equality check done on `ContextWebFilter.kt` which check the equality without checking if there is variables.

**To Reproduce**
Put a variable to your graphql endpoint and try to access the graphql Context in a query. There will be an error thrown :  `Exception while fetching data (getProjects) : argument type mismatch`

**Expected behavior**
The graphql context may need to be populated even if the paths are not equals if there is path variables.

**Comment by dariuszkuc** [comment]
Thank you for raising this. Indeed currently we don't support parameterized paths. AFAIK this is not a common use case and instead this path parameter would generally be passed as one of the query input arguments.

Some potential fixes/workarounds:
* update the path matching logic to use regex instead of string comparison
* do nothing - while currently it is not possible to disable the context web filter, technically as a workaround you could still configure second custom webfilter that accounts for path parameters. In this case even though two webfilters would be applied, generic context one would be skipped anyway. We could look into exposing some configuration property to disable the default context web filter as well.
* migrate from web filter to handler filter - while it would apply only on the graphql route we would loose the option to specify other web filters after the context

I'm also open to suggestions for some other approaches.

**Comment by guillaumeNaimi** [comment]
I think the first approach should be the best knowing that the rest of the lib works fine with parametrized paths. I can try to submit a PR if you want.

**Comment by dariuszkuc** [comment]
> I think the first approach should be the best knowing that the rest of the lib works fine with parametrized paths. I can try to submit a PR if you want.

The only problem is that in order to fully support path variables (as per [RFC3986](https://tools.ietf.org/html/rfc3986)) you need a pretty nasty regex to handle all of the `A–Z`, `a–z`, `0–9`, `-`, `.`, `_`, `~`, `!`, `$`, `&`, `'`, `(`, `)`, `*`, `+`, `,`, `;`, `=`, `:`, `@`, as well as `%` that must be followed by two hexadecimal digits. 

@smyrick any thoughts on this?

**Comment by dariuszkuc** [comment]
I guess we could also just accept anything the parameterized path, something like

```
    private fun generateGraphQLRoutesRegex(graphQLRoute: String, subscriptionRoute: String): Regex = "$graphQLRoute|$subscriptionRoute"
        .replace("\\{\\w+}".toRegex(), ".+")
        .toRegex(RegexOption.IGNORE_CASE)
```

**Comment by dariuszkuc** [comment]
@guillaumeNaimi with the #458 you can extend the default context web filter with more complex pattern matching.
