### ISSUE TITLE
Find replacement for use of google guava

### ISSUE THREAD

**Issue by larslorenzen** [ExpediaGroup/graphql-kotlin#459]
Hi, i just noticed, that you require google guava for graphql-kotlin-schema-generator.

But you only use one class `CaseFormat` from the ~2.6M library. 
Would it make sense to implement the directive name normalizing directly and remove the dependency?
Or is this perhaps a valid replacement: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/decapitalize.html ?

Found in version: 1.3.0

**Comment by dariuszkuc** [comment]
Great callout! I don't think we need guava. We used it originally as it was a transitive dependency on  the reflections lib (https://github.com/ronmamo/reflections). Since we moved away from it I think we should remove this unnecessary dependency.

**Comment by smyrick** [comment]
Good call out @larslorenzen! Marking as new request. We will gladly accept a PR if you think there is a better replacement

**Comment by smyrick** [comment]
Actually I am going to just verify now if we can just drop in replace this. I believe we can since class names in Kotlin follow the convention of being upper-camelcase ie `MyCustomClassName`

Directives in GraphQL should be the same but just lowercase first letters. If you want to set a custom name format you can still to that with `@GraphQLDirective(name = "CustomName")`

**Comment by larslorenzen** [comment]
The PR looks good, that's what i tried too :) 
Functionality seems to be tested well already.
