### ISSUE TITLE
Every graphql codegen stop with server side. Why no java client generator?

### ISSUE THREAD

**Issue by anborg** [ExpediaGroup/graphql-kotlin#470]
The same schema and query can be used for client generation.

Can you please tweak the server code generators to also generate, client java classes for graphql types, and marshaler that converts json to client java classes?

**Comment by anborg** [comment]
The same schema and query can be used for client generation. 

Can you please tweak the server code generators to also generate, client java classes for graphql types, and marshaler that converts json to client java classes?

**Comment by smyrick** [comment]
Hello @anborg, thank you for your feature request.

This library currently takes Kotlin code and generates a GraphQL schema to run a GraphQL server. Doing the reverse, is not as simple as a small tweak.

However there is a library from the Apollo team which does exactly what you are looking for. Is has Android in the name but there is nothing Android specific. We have seen Java clients using this library in production

https://github.com/apollographql/apollo-android



Since this code already exists I am going to close this request as we do not have plans to implement client code generation in GraphQL Kotlin
