### ISSUE TITLE
How to download generated scheme

### ISSUE THREAD

**Issue by kovac777** [ExpediaGroup/graphql-kotlin#498]
How to download generated scheme?

**Comment by dariuszkuc** [comment]
If you are using `graphql-kotlin-spring-server` it automatically exposes `/sdl` endpoint that returns it, otherwise you may have to create one yourself (see https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt#L78).
