### ISSUE TITLE
Hooks for isValidProperty() and isValidFunction() should have the KClass as an argument

### ISSUE THREAD

**Issue by cwendel16834** [ExpediaGroup/graphql-kotlin#526]
### Problem
The automatic generation adds all properties and functions to my output and input types. For instance, the `id` property of an entity class makes sense on an output type, but is not appropriate for an input type. By looking only at the KProperty, I am not able to determine if my KClass is an input type in order to selectivly disable this generation.

### Proposed Solution
It would be helpful to pass the KClass as an argument to these hooks so that the parent class may influence whether a property or function is valid for type generation.

### Alternatives
I have been unable to find a way to determine the parent KClass of a KProperty from the KProperty instance alone. It is possible there is a way I have not discovered yet.

**Comment by dariuszkuc** [comment]
Thanks for raising this. 

As you mentioned depending on the use case we may want to have slightly different objects for input and output. That is also why GraphQL spec makes a distinction between input and output types and treats them separately. Since we are using reflections to generate the schema, we can easily generate both types from single class (with only distinction that we don't expose functions on input types as it doesn't make much sense to do so). I'd advise against conditionally hiding some fields as it could lead to some problems with serialization (e.g. in your example above for your input if you don't expose `id` you would have to make it nullable).

That being said, I agree that those hooks should take their `KClass` as an argument to make them more usable.

**Comment by cwendel16834** [comment]
Happy to help!

Over the weekend I was exploring this idea and found it immensely helpful
to include the KClass and the type of object being generated (Object,
InputObject, Subscription, Mutation, etc.) in the isValidFunction() and
isValidProperty() calls. These additions provided the flexibility I needed
to get a generated schema that suited my needs.

**Comment by cwendel16834** [comment]
The more I think about it, I am probably organizing my classes improperly. I was taking in my entity class (`Player`) on the `addPlayer(player: Player)` mutation when I should possibly take in a different class or set of params specifically for initializing a `Player`. Does that sound right to you? If I do this, my needs to modify the generated schema go down quite a bit.

**Comment by dariuszkuc** [comment]
You certainly could use the same object (`Person`) for both query and mutation but you might have a problem with how to treat the primary key `id`, e.g. I'd assume it would be something auto-generated by the backend so it would be available when you run your query and also would be required for update operations but you generally wouldn't specify it for insert operations. If you were to use the same data class for all use cases then you would have problem with how to deserialize the input - you could make it work by making `id` nullable but it would incorrectly relax the type for query/update operations. 

Each one of your clients would generate their model based on their queries - it doesn't really matter if you have separate objects representing read (query), add or update (mutation) operations. GraphQL encourages denormalization so you could have some very specific operations with appropriate inputs.
