### ISSUE TITLE
DataLoaderRegistryFactory is not available in subscription

### ISSUE THREAD

**Issue by EugenePisotsky** [ExpediaGroup/graphql-kotlin#602]
Hello,

I can't access DataLoader in subscription, probably because it's not passed here as the second argument to `toExecutionInput` method:
https://github.com/ExpediaGroup/graphql-kotlin/blob/c97eab8275fc099a7f3d9d5e94954f101ba8a371/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandler.kt#L50

Is it intended?

**Comment by killercup** [comment]
Hey, sorry to resurrect this closed issue, but I seem to be having the same issue. I tried supplying my own [SpringGraphQLSubscriptionHandler](https://github.com/ExpediaGroup/graphql-kotlin/blob/8af160bad1382e61a9ca17cd0a29398cb93c861d/servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt), but the only method on the class is final… so that led nowhere.

Did you or anyone else find a solution for this?
