### ISSUE TITLE
Create a homepage for docs

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#605]
The documentation home page today is just the Getting Started page. We could create a docusaurus landing page so we can have a more visual appealing site to view and that is SEO friendly.

See: https://docusaurus.io/

**Comment by DelfCo** [comment]
We moved to a standalone help site some time ago: https://expediagroup.github.io/graphql-kotlin/docs/getting-started.html

That's built out of the `docs` directory, and started life by being copied from the wiki pages.

**Comment by EXPErdelfavero** [comment]
Oops. That was me up above, misunderstanding the question and logging in with my personal Github ID instead of my work ID. The point of this bug is to add that new landing page to the existing site I pointed to in the previous comment. It's a standard Docusaurus setup, and the easiest way to start is probably to create a new, empty Docusaurus site and grab the home page generated there, add it to the right place in this repo, and fill in the details.

**Comment by smyrick** [comment]
This is no longer needed now that we have adopted the "docs only" approach with docusaurus v2. Our base url now is just the getting started page

https://expediagroup.github.io/graphql-kotlin

**Comment by dariuszkuc** [comment]
I believe the intent was to have something nicer and more visual as a landing page. Technically it was not "needed" in docusaurus v1 either as we were redirecting stuff to getting started docs anyway.
