### ISSUE TITLE
Some dependencies contain CVEs

### ISSUE THREAD

**Issue by sewilguler** [ExpediaGroup/graphql-kotlin#625]
**Library Version**
2.0.0-RC9

**Describe the bug**
Hi,
I found io.netty 4.1.45 that is used in your project has some security problem. 
 
See below for more details:
<img width="1435" alt="Screenshot 2020-02-28 at 10 36 41" src="https://user-images.githubusercontent.com/7179520/75537526-9348f080-5a17-11ea-9f2c-47b7fff45ffd.png">

Overview
org.wso2.transport.http:org.wso2.transport.http.netty is a HTTP protocol handling implementations for C5 based products.

Affected versions of this package are vulnerable to HTTP Response Splitting due to HTTP Header validation being disabled.

Remediation
Upgrade org.wso2.transport.http:org.wso2.transport.http.netty to version 6.3.1 or higher.

References:
CONFIRM - https://snyk.io/vuln/SNYK-JAVA-ORGWSO2TRANSPORTHTTP-548944

**Comment by sewilguler** [comment]
The dependency causing the problem added by org.springframework.boot:spring-boot-starter-reactor-netty:2.2.4.RELEASE which comes with org.springframework.boot:spring-boot-starter-webflux:2.2.4.RELEASE

**Comment by smyrick** [comment]
It looks like Spring 2.2.5 was released with this fix just yesterday: https://spring.io/blog/2020/02/27/spring-boot-2-2-5-released

We can upgrade our dependency then

**Comment by smyrick** [comment]
It looks like you were using this product to find security reports: https://snyk.io/product/

There are lots of security tools out there but we have not added one in graphql-kotlin yet other than the Github security alerts. This would be a good thing to add to our library

**Comment by sewilguler** [comment]
Hi @smyrick,

Thank you so much for the help. I have a scheduled gradle task on my project running org.owasp.dependencycheck: 5.3.0 every 6 hours. So it is alerting whenever there is a new security issue. Thanks again for the help. Have a nice weekend.

**Comment by sewilguler** [comment]
Hi @smyrick,

Problem actually still exists. And security fixes they made is not CVE-2019-10797. This link might help: netty/netty#10059.

**Comment by smyrick** [comment]
Ah, ok. Thank you for checking. I was too quick to assume that a CVE fix in the release for Reactor Netty was the same issue.

As far as things that we can do to resolve this error, there is not much if the issue has not been fixed in Netty yet. Even after it is fixed since we don't directly depend on Netty the only thing we can do is to try to force Gradle to the newer dependency version until Spring Boot is updated. Instead of doing that in the library though I think we would leave that up to the end server developers to resolve.
