### ISSUE TITLE
Sealed classes not treated as abstract

### ISSUE THREAD

**Issue by userkci** [ExpediaGroup/graphql-kotlin#642]
**Library Version**
What version are you using?
1.4.2

**Describe the bug**
Sealed classes only generate a Type capturing their own class.

**To Reproduce**
Given the following class hierarchy:

```
sealed class Pet(val name: String) {
  data class Dog(name: String, val goodBoysReceived: Int) : Pet(name)
  data class Cat(name: String, val livesRemaining: Int) : Pet(name)
}
```

The resulting schema generated is:

```
type Pet {
  name: String!
}
```

**Expected behavior**
The expectation is that the sealed class defines an Interface/Union (as appropriate) and each subclass generates a type, such as below:

```
interface Pet { 
  name: String!
}

type Dog implements Pet {
  name: String!
  goodBoysReceived: Int!
}

type Cat implements Pet {
  name: String!
  livesRemaining: Int!
}
```

It looks like this is due to `KClass.isAbstract` returning false for a sealed class and therefore ` KClass<*>.isInterface()` does too. Digging into the Kotlin source this is simply a check if the modality of the class is `ABSTRACT`, but the modality is an enumeration of `OPEN`, `FINAL`, `ABSTRACT`, and `SEALED`. So I'd suspect that adding `KClass.isSealed` to the interface check would suffice.

**Comment by smyrick** [comment]
@userkci Thank you for reporting this issue! It appears that we did not consider this when implementing the library, but it seems possible to support.

We will merge this into the master branch because I consider this a new feature we did not implement yet, so that means it will be available in the 2.x.x branch.

If you would like to provide a pull request to get this in sooner, please feel free to assign yourself to the issue, otherwise we won't wait to get this in the 2.0.0 release which means it may come out as a 2.1 release.
