### ISSUE TITLE
DataLoader used by `suspend` function fails to complete

### ISSUE THREAD

**Issue by rharriso** [ExpediaGroup/graphql-kotlin#659]
**Library Version**

1.4.2

**Describe the bug**

When I use a `BatchLoader` to resolve a property defined as a suspended function the request will complete maybe once or twice, and then subsequently fail to complete. The `Dataloader` body 

If I define the property as a function that returns a `CompletableFuture` it returns successfully every time.

This may be expected behavior. If so I'd like to update the example code.

**To Reproduce**

1. Check out the following branch https://github.com/rharriso/graphql-kotlin/tree/demostrate-batch-issue
2. Run the spark example
3. Request the suspended property multiple times:
```graphql
query {
  searchCourses(params: { ids: [1,2,3] }) {
    university {
      id
      name
    }
  }
}
```
4. See complete once or twice and fail afterwards.
5. Query the property supplied by `CompletableFuture`
```graphql
query {
  searchCourses(params: { ids: [1,2,3] }) {
    universityFuture {
      id
      name
    }
  }
}
```
6. This query should always succeed.

**Expected behavior**

Not sure. If this is a bad usage of a batch loader I'd like to know.

**Comment by smyrick** [comment]
I don't see the benefit of declaring using `suspend` functions with `DataLoader` as this just caches the response to be used at a later time. Since we convert the type internally on `suspend` functions, if `DataLoader` expects a `CompletableFuture`, you will have to return that.

However if you want to keep in coroutines could you implement your own caching server side inside the coroutine scope. Also you don't need to make your queries `suspend` just to call an internal service that makes some IO operation. You could instead define the scope on your service call and run that `async` and have it return a standard function so you can call it from a regular `CompletableFuture` function

**Comment by rharriso** [comment]
> if DataLoader expects a CompletableFuture, you will have to return that.
I don't think there is a way for them to support co-routines since the library is implemented with Java/

My use-case makes a network request to another service over gRPC.

I'll update the spark example to include asynchronous example.

**Comment by dariuszkuc** [comment]
Unsure if that is the problem but you are using `Thread.sleep` from coroutine call in `BatchUniversityLoader` which means that you are blocking the coroutine there.

**Comment by smyrick** [comment]
I am going to close this issue as we can update the examples with other ways to use data loader.

**Comment by DrMetallius** [comment]
> I don't see the benefit of declaring using `suspend` functions with `DataLoader` as this just caches the response to be used at a later time.

The example provided by the original poster is contrived indeed, but the benefit here is simple: I get some result from another service through a loader, then I use it differently in different resolvers. Obviously, I don't want to call said external server multiple times in the same query, that's why I need some mechanism for batching and caching.

I can't just move the logic from the resolvers into a data loader. I have one external service, but the result is used differently by different resolvers, so that would result in different data loaders thus defeating the purpose. The only way of making this work that I can see is by abandoning coroutines altogether and transforming the `CompletableFuture` from the data loader via `thenApplyAsync` or something similar. Obviously, this doesn't exactly thrill me as it's neither consistent, nor convenient.

**Comment by jbrwn** [comment]
I just hit this today as well and have the same use case as @DrMetallius.  Abandoning `suspend` functions and returning `CompletableFuture` when using `DataLoader` does "solve" the problem but as noted above this does not really seem consistent or convenient especially when you end up having to transforming CompletableFutures.   

This example is also a bit confusing since it uses a pattern that doesn't seem to work and, as mentioned above by @smyrick, is not actually recommended.  

https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/models/Course.kt#L38
