### ISSUE TITLE
Receive files sent via apollo client on a spring-boot back-end

### ISSUE THREAD

**Issue by gonzalt03** [ExpediaGroup/graphql-kotlin#661]
The configuration of the spring-boot with graphql will it manage basic multipart requests made by Apollo client ?
Do you have an example of a complete and functional file sending implementation on a spring-boot graphql back-end?
As it stands, a 400 BAD REQUEST is returned by the spring-boot. I do not understand why. The request is however well recognized by the ContextWebFilter in the graphql-kotlin-spring-server library.

**Comment by dariuszkuc** [comment]
Apollo file uploads are not part of the GraphQL specification are not supported "out-of-the-box". As per https://github.com/ExpediaGroup/graphql-kotlin/issues/518 you will have to configure Jackson object mapper to correctly handle those types (and potentially also configure custom data fetcher to apply the custom logic - if needed).

**Comment by ilaborie** [comment]
Hi @gonzalt03 ,

We have trying to do the same thing, you can check this [gist](https://gist.github.com/ilaborie/cde26929dbe685c74682fb01817e37c3) to see how we have implement the behavior.

**Comment by ilaborie** [comment]
This week, we'll be take the time to create the PR on that issue soon.

**Comment by smyrick** [comment]
At this time we don't have intention to add support for this feature as it is not directly related to running a server and is more of a specific data feature.

I am going to close this issue, but feel free to continue to document your learnings for others here.

**Comment by rharriso** [comment]
I wanted to comment on how I was able to implement file uploading.

_Note: I am using S3 for asset hosting_

1. Request pre-signed upload URL from graphQL service (Reject or grant URL based on user permissions)
2. Upload asset directly to pre-signed URL from client (browser in my case)
3. Include include URL in subsequent mutation. The back-end service can then access the uploaded file from the S3 bucket as neccessary.

This works well for me, since the GraphQL server is an API gateway and file processing is done by another service. This allows me to deliver reference the uploaded file when communicating between services, rather than passing a large binary blob that might not even be processed.
