### ISSUE TITLE
ignoring Kotlin generic interfaces

### ISSUE THREAD

**Issue by Wayne-P** [ExpediaGroup/graphql-kotlin#687]
graphql-kotlin-spring-server 2.1.1

Greetings, I am trying to get up to speed with both Kotlin and graphql, so your software seems to be very promising.

A newbie question though - if I have a class such as
```kotlin
data class Portion2 constructor(
    val str: String
): Comparable<Portion2> {
    override fun compareTo(other: Portion2): Int {
        return compareValuesBy(
            this, other,
            Portion2::str
        )
    }
}
```
which would form the source of a graphql schema, then it seems that it does not compile owing to its extension of a generic interface.

However, at the same time, I would not be able to add an `@GraphQLIgnore` anywhere.
As I cannot modify `kotlin.Comparable`, or at least I do not think I can extend it with an interface annotation, I tried 
```kotlin
data class Portion2 constructor(
    val str: String
): @GraphQLIgnore Comparable<Portion2> {
    override fun compareTo(other: Portion2): Int {
        return compareValuesBy(
            this, other,
            Portion2::str
        )
    }
}
```
without success.

Am I missing something obvious here, as it seems like a common situation ?

**Comment by dariuszkuc** [comment]
Hello! In order to exclude those interfaces/superclasses from the schema you will have to configure a schema generator hook to do it. See https://github.com/ExpediaGroup/graphql-kotlin/pull/657 for example use case (specifically [isValidSuperclass](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomSchemaGeneratorHooks.kt#L56) hook).

**Comment by Wayne-P** [comment]
Many thanks, for your time. I shall look into the isValidSuperclass hook.
