### ISSUE TITLE
@GraphQLID support for List<ID>

### ISSUE THREAD

**Issue by lennyburdette** [ExpediaGroup/graphql-kotlin#698]
I might be missing something—is it possible to use the `@GraphQLID` annotation on a `List<String>`? 

```kotlin
class Query {
  fun thingsByID(@GraphQLID ids: List<String>): List<Thing> = ...
```

When version 2.1.1, I get:
```
com.expediagroup.graphql.exceptions.InvalidIdTypeException: List is not a valid ID type, only Strings are accepted
```

I have a workaround, but I wanted to check to see if I was just doing something wrong:
```kotlin
typealias ID = String

class Query {
  fun thingsByID(ids: List<ID>): List<Thing> = ...
}

class CustomSchemaGeneratorHooks(
  federatedTypeRegistry: FederatedTypeRegistry
) : FederatedSchemaGeneratorHooks(federatedTypeRegistry) {
  override fun willGenerateGraphQLType(type: KType): GraphQLType? = when (type.classifier as? KClass<*>) {
    ID::class -> Scalars.GraphQLID
    else -> super.willGenerateGraphQLType(type)
  }
}
```

Thanks!

**Comment by smyrick** [comment]
@lennyburdette Unfortunately there is not a better way right now to accomplish a GraphQL list of ids (`[ID]`) in a better way than what you have commented with setting custom hooks.

We had a discussion about this when changing the annotation support to only work on strings about including a wrapper `ID` type. https://github.com/ExpediaGroup/graphql-kotlin/issues/317

At the time though we had used a full class and not a typealias. Does the typealias show up in the reflection check? Because if it does we could include this in the library so you could use the typealias or the annotation.

**Comment by smyrick** [comment]
I did a little code check locally and the check `type.classifier == ID::class` returns true because ID::class is just `String` so this doesn't actually tell us if you have used `List<ID>` or `List<String>`

**Comment by smyrick** [comment]
I suppose we could go back to creating a wrapper class that only accepts a String value. This could mean we could clean up a lot of the logic we have around having to pass the `annotatedAsID` boolean around because we lose the annotation information

```kotlin
/**
 * Used to represent a GraphQL ID scalar type
 * which must serialize to a string value
 */
class ID(val value: String)
```

**Comment by lennyburdette** [comment]
Awesome! Not expecting a blazing fast response!

I'm all for a wrapper type if that's the direction you decide to go. I had a few moments to try to support the annotation and I think I have it working: https://github.com/ExpediaGroup/graphql-kotlin/compare/master...lennyburdette:lenny/support-lists-of-ids?expand=1

But I agree that passing the `annotatedAsId` around everywhere isn't fun.

**Comment by knrybarczyk** [comment]
wow, fantastic guys, thanks a ton for making this happen so quickly, I've just hit this issue with the previous version and I'm now happily back to my work using the 3.0 RC :)
