### ISSUE TITLE
GraphQLDescription does not output the hash symbol as part of the output

### ISSUE THREAD

**Issue by rajkumar1979** [ExpediaGroup/graphql-kotlin#774]
**Library Version**
What version are you using? 3.1.1 . I am using Mac

**Describe the bug**
When I add @GraphQLDescription to the kotlin data class , the generated schema does not show the hash tag as part of the Schema definotion

 @GraphQLDescription("demo description ")
val id: int

Generated Schema
type Candidate {
  "demo description"
  id: Int!
}

**Comment by dariuszkuc** [comment]
GraphQL descriptions should use quotes -> see https://spec.graphql.org/June2018/#sec-Descriptions
GraphQL comments use # -> https://spec.graphql.org/June2018/#sec-Comments

We currently don't support comments.

**Comment by rajkumar1979** [comment]
This is what I am currently doing in my kotlin file.

@GraphQLDescription("Unique identifier for a new candidate record at the time of creation and will remain constant for the duration of existence")
 var id: Int

but when the schema gets written the output it gets printed as

"Unique identifier for a new candidate record at the time of creation and will remain constant for the duration of existence"
  id: Int!

**Comment by smyrick** [comment]
@rajkumar1979 According to the spec, GraphQL field descriptions are marked with either `"` or `"""`. 

```graphql
type Foo {

  "I am a spec compliant description"
  id: String!

  # I am a SDL comment that is not included officially in field descriptions
  """
  I am a multi-line
  comment on the value field with "quotes" inside
  """
  value: String

}
````

If you are migrating from `graphql-java`, it incorrectly used `#` in the printed schema for field descriptions in older versions. This was fixed in [graphql-java 14](https://github.com/graphql-java/graphql-java/pull/1609)

If you want to keep this broken behavior you can use the graphql-java `SchemaPrinter` yourself and print the schema with the [deprecated descriptionsAsHashComments option](https://github.com/graphql-java/graphql-java/blob/a9f7932266b3cc8395123994f0b9675ad2ab642e/src/main/java/graphql/schema/idl/SchemaPrinter.java#L106)

**Comment by rajkumar1979** [comment]
@smyrick thanks , did not know that double quotes are compliant.
