### ISSUE TITLE
relay compatibility

### ISSUE THREAD

**Issue by rajkumar1979** [ExpediaGroup/graphql-kotlin#776]
are there any examples for relay compatible schemas.

**Comment by smyrick** [comment]
Relay is a GraphQL client library, so as long as you are talking to a GraphQL spec compliant server (which `graphql-kotlin-spring-server` is) then examples of Relay have nothing to do with this library.

You should instead consult the relay docs: https://relay.dev/

**Comment by smyrick** [comment]
@rajkumar1979 It seems you have quite a few questions about GraphQL, and not about the specifics of this library implementation. I would first make sure you understand the GraphQL eco-system regardless of the language or libraries used as that may help you answer some of your questions.

https://graphql.org/learn/

**Comment by smyrick** [comment]
So looking further into relay (I have not used it before), it appears it requires some specific types to be in the schema

https://relay.dev/docs/en/graphql-server-specification.html

We don't control what types you have in the schema, so since it just builds on top of GraphQL, as long as you match what the client is expecting you should be able to create a relay compatible GraphQL server.

**Comment by smyrick** [comment]
It looks like `graphql-java` has some built-in support for relay so you would have access to these types, you just need to include the packages in the configuration of the generator

https://github.com/graphql-java/todomvc-relay-java
