### ISSUE TITLE
Sample Project for usage including tests

### ISSUE THREAD

**Issue by huehnerlady** [ExpediaGroup/graphql-kotlin#779]
Hi,

it seems very easy to use this library but I run in issues regarding tests of the service using the generated query item.
I need to mock it, so far I am trying to use mockk for it.

When I mock this call using the "runBlocking", I get the error `class java.lang.Object cannot be cast to class com.expediagroup.graphql.types.GraphQLResponse (java.lang.Object is in module java.base of loader 'bootstrap'; com.expediagroup.graphql.types.GraphQLResponse is in unnamed module of loader 'app')`

code:
```kotlin
        every {
            runBlocking {
                myQuery.execute(any())
            }
        } returns GraphQLResponse()
```

If I try to mock without the `runBlocking` wrapper, I get the error `Suspend function 'execute' should be called only from a coroutine or another suspend function`
code:
```kotlin
        every {
            myQuery.execute(any())
        } returns GraphQLResponse()
```

I tried to find a sample where this is being mocked, but so far I just found the documentation about how to use it in production code, not how to mock it.

**Comment by dariuszkuc** [comment]
Hello, your questions are specific to the usage of `mockk` library so probably they would be better placed there. See https://mockk.io/ for that library documentation. 

`myQuery.execute` is a suspendable coroutine call which means it has to run within a coroutine scope. You could wrap your whole test case in `runBlocking` (you should not be doing it from `every` block) but I think you are probably looking for `coX` family of functions (e.g. `coEvery` instead of `every`). 

As for your error -> `class java.lang.Object cannot be cast to class com.expediagroup.graphql.types.GraphQLResponse` it means the passed in mock does not have enough information to determine the proper type and is defaulting to `Any` (java `Object`). You will need to explicitly pass type e.g. `any<ABC>()`.

**Comment by huehnerlady** [comment]
@dariuszkuc many thanks for your help. I wasn't sure where to put this, but also thought might be a good poke for you to add some tests in your example-project? 😉 

Got it to work now though, thanks
