### ISSUE TITLE
Support to see if user set field explicitly to `null` on input object

### ISSUE THREAD

**Issue by natashashams** [ExpediaGroup/graphql-kotlin#783]
**Context**
I am trying to create a mutation to allow partial updates an object with many nested fields.
`fun updatePersonInfo(request: UpdatePersonInfo): Profile?`
nested fields are all optional, so the user only needs to supply fields they want to update in the request.

Fields absent from request will be not be changed.
Fields present in the request will be set to the newly values defined in request, including fields set to `null`.

Example --
a mutation to set familyName to "natasha-new-family-name" and middleName to `null` would look like:
```
mutation myMutation {
  updatePersonInfo(
    userId: 123,
    personInfo {
      “name”: {
        “familyName”: “natasha-new-family-name”, 
        “middleName”: null
      }
    }
  )
}
```

a mutation to only update family name, leaving middleName unchanged, would look like:
```
mutation myMutation {
  updatePersonInfo(
    userId: 123,
    personInfo {
      “name”: {
        “familyName”: “natasha-new-family-name”
      }
    }
  )
}
```

**Problem**
I am unable to cleanly use graphql-kotlin to see if a user has set a field to _null_  in the mutation input object (indicating desire to delete a field) because there is no way currently to differentiate if a field was set to null by the user, or if it was simply never defined (absent in request).

This is also nature of kotlin itself, undefined fields default to `null` as the value. However, in graphql there is a difference between undefined and set to `null` that I am hoping to leverage. https://graphql.github.io/graphql-spec/June2018/#sec-Input-Objects (see: Input Coercion)

**Proposed Solution**
A wrapper class built-in to graphql-kotlin such that a field can have three values to represent it (undefined, null, value). This wrapper would not show up in the schema definition of the object, but would be used to represent if the object it wraps was present in the request or not. If it was present, it's value is also defined.

Alternatively, leverage java optional wrapper to do this, where the optional wrapper would also not show up in the schema type.

**Alternatives**
Since I do not want the wrapper shown in the schema, my current solution is to parse through the available graphql-java DataFetchingEnvironment instead of using the input object itself (input object still defined for user input) to see if fields are present in the request or explicitly set to null (indicates desire to delete).

As a temporary solution, I wanted to create this wrapper myself, however it would show up in schema. Hoping a built-in optional wrapper supported by graphql-kotlin could help this...

**Additional context**
A similar question has already been asked in this thread:
https://github.com/ExpediaGroup/graphql-kotlin/issues/50#issuecomment-483432882
but I feel the root of the problem was never addressed/answered in the original thread.

**Comment by smyrick** [comment]
This has come up in the client generation too. If we wanted to support this we would need logic to handle both the following functions

```kotlin
fun optionalInput(value: String?) = value
fun optionalInput(value: Optional<String?>) = value.get()
```

I think unwrapping an optional for you is fine and we could add that logic to the library, however the logic to now handle the simple case becomes tricky because now we are not forwarding the same information and I think we still want to support the first case.

------

One way you could implement this is by checking the `DataFetchingEnvironment` to see what fields and arguments were selected

```kotlin
fun optionalInput(value: String?, dataFetchingEnvironment: DataFetchingEnvironment): String =
        if (dataFetchingEnvironment.containsArgument("value")) {
            "The value was $value"
        } else {
            "The value was undefined"
        }
```

Then you can see this example output is the result. While it is more logic in the function I think this allows us to handle both cases where devs may or may not be interesting in when the value is undefined vs null

<img width="1266" alt="Screen Shot 2020-06-30 at 11 03 43 AM" src="https://user-images.githubusercontent.com/2446877/86161432-18c1d780-bac2-11ea-8208-6a5f5d1becae.png">

**Comment by natashashams** [comment]
Got it. For especially large, nested objects, using `DataFetchingEnvironment` is much more internal logic, but it is a do-able workaround for now. 

Also considering using [scalars](https://expediagroup.github.io/graphql-kotlin/docs/schema-generator/writing-schemas/scalars) as a way to make internally wrapped classes appear "unwrapped" in the schema. Haven't tried it out yet, but will take a look.

Thanks for the quick response!

**Comment by dariuszkuc** [comment]
The underlying problem is that GraphQL spec was based on Javascript implementation where there is a clear distinction between undefined and `null` value. In JVM world any object either has specific value or is `null` (i.e. which means no value). Using optionals is just a nicer way of dealing with `null` values but I don't think it would resolve the underlying issue, e.g.

```kotlin
val explicitNullValue: String? = null
val optional: Optional<String> = Optional.ofNullable(explicitNullValue)
println(optional.isPresent)  // false
println(optional.isEmpty)    // true

val empty: Optional<String> = Optional.empty()
println(empty.isPresent)    // false
println(empty.isEmpty)      // true
```

Whether we have empty optional or optional with null value they both behave the same way. In order to actually have the "3rd" state you would need to make the actual optional nullable which seems pretty hacky to me (better approach would be to use specific classes as suggested in https://github.com/ExpediaGroup/graphql-kotlin/issues/50#issuecomment-483806428)....

```kotlin
fun optionalInput(value: Optional<String>? = null)
```

**Comment by oatmeal-raisin** [comment]
@natashashams It seems like there is a really good start at https://github.com/OpenAPITools/jackson-databind-nullable that works with javax validation and Jackson. Another benefit is that it is not overloading Optional. I haven't looked at what it would take to make sure the type does not show up in the schema and to have it properly plugged into the marshalling that is happening in graphql-kotlin.

**Comment by oatmeal-raisin** [comment]
Looking at this further it seems like having more flexible monad resolution would help here. It is more generic feature than just supporting optional. Again I am not sure exactly how to plug this in because I am still learning some of the details of this framework. The current will resolve monad will not work because these are properties. Is there a recommended approach for this @dariuszkuc ?

**Comment by natashashams** [comment]
thanks for all the input! We have added a custom wrapper class (similar to https://github.com/ExpediaGroup/graphql-kotlin/issues/50#issuecomment-483806428) which is the cleanest solution if I want to avoid parsing through the DataFetcherArgument map.

However, we can seem to figure out the best way to unwrap and only expose the inside of this wrapper to the user during schema generation. The `willResolveMonad` hook looks like it does something similar to what we need to hide this wrapper from the user schema, however it is only called on return types and at the top level objects at the moment.

@smyrick or @dariuszkuc can this method be modified to also be invoked on input types, and nested fields within those input types? Or is there an alternative to this already in the library that I don't know about?

**Comment by dariuszkuc** [comment]
While it is possible to achieve this with the current hooks it is somewhat problematic, i.e. you could use `willGenerateGraphQLType` to process the wrapper class but since hooks don't have access to the generator you would need to manually build underlying GraphQL type (or reference built in scalars). Once schema is generated you would still need to create custom data fetcher to properly unmarshall the incoming object into the wrapper class.

I'm thinking for `4.0.0` we probably could introduce some sealed class to represent defined/undefined state (introduce the unwrapping logic in input object generation and update default data fetcher to properly handle those as well).

**Comment by smyrick** [comment]
I have a very early WIP branch here. I am having issues with the deserialization of the generics. I don't know how in this [line](https://github.com/ExpediaGroup/graphql-kotlin/compare/master...smyrick:maybe-defined?expand=1#diff-4f945ef48015f4dcb2229f8f37b1c5dfR52) I can set the value of the `MaybeDefined.Defined()` to the value of the `JsonNode` if the json node can be multple different types and the only good way to get the value of the JsonNode is `asText()` which will convert any value to String, so if we have a `MaybeDefined<Int?>`, how do we convert it back with out have to to have checks for all supported scalars?

https://github.com/ExpediaGroup/graphql-kotlin/compare/master...smyrick:maybe-defined?expand=1

**Comment by dariuszkuc** [comment]
I was playing around with Jackson trying to get the correct behavior and deserialization works correctly if you use Java 8 module and nullable optional with default value null (note that omitting default value results in incorrect behavior), e.g.

```kotlin
data class TestResult(val maybe: Optional<String?>? = null)
fun main() {
    val mapper = jacksonObjectMapper()
    mapper.registerModule(Jdk8Module())
    val undefined = "{}"
    val nullValue = """{ "maybe": null }"""
    val value = """{ "maybe": "actual" }"""
    val undefinedValue = mapper.readValue(undefined, TestResult::class.java)
    println(undefinedValue)
    val explicitNull = mapper.readValue(nullValue, TestResult::class.java)
    println(explicitNull)
    val withValue = mapper.readValue(value, TestResult::class.java)
    println(withValue)
}
```

this prints out
```
TestResult(maybe=null)
TestResult(maybe=Optional.empty)
TestResult(maybe=Optional[actual])
```

So while ugly you could potentially register optionals with your schema through the hooks and that "should" work.

**Comment by oatmeal-raisin** [comment]
@dariuszkuc, @smyrick I was able to get this to work by adding a hook into generateGraphQLType in a local build of graphql-kotlin. The hook was basically the equivalent of willResolveMonad. Leveraging that hook and Jackson's support for Optional worked in @natashashams and I project. generateGraphQLType is probably no the ideal place for this but it helped me prototype it quickly. It would be great to add a hook that allowed you to unwrap types, even if a built in type will be provided for undefined. These cases would require users to write their own deserializers but it's a very generic feature that could help as a stepping stone to related wrapper functionality. It would be especially helpful if someone is looking to map to a type that is more natural to deeper layers of their service.
