### ISSUE TITLE
Support read-only fields

### ISSUE THREAD

**Issue by rhys-saldanha** [ExpediaGroup/graphql-kotlin#872]
When exposing objects that have generated fields, for example a database-generated ID, I would like to be able to mark these fields as 'read-only'. With this marker, I would be able to define a single object with all necessary fields (ID, name, age, etc.). Any fields marked as read-only would appear in my Query schema, but not in my Mutation schema.

My proposed solution is to add an `@GraphQLReadOnly` annotation, which can be applied at the field level to data classes.

```
data class Widget(@GraphQLReadOnly val id: Int?, val value: String)
```

I believe the current advice is to create two data classes, one with all fields for Queries (say, `Widget`) and one with only the mutable fields for Mutations (say, `WidgetInput`). This duplication of classes is something I would like to avoid, if possible.

**Comment by dariuszkuc** [comment]
Hello! Thanks for raising this issue but unfortunately we will not be adding this functionality to the core library.

As you mentioned, even though it is possible to generate input and output from the same Kotlin data class it is not something that we would recommend. There are many problems with reusing the same type where only a subset of fields would be used for input/output - the biggest one is that in order to satisfy compiler safety you would need to either mark the id field as nullable (as in the example above) which seems wrong for the output type or make it non nullable (so it has correct output type) and initialize it with some dummy value (which input would ignore). 

That being said you should be able to achieve this functionality either through custom hooks (https://expediagroup.github.io/graphql-kotlin/docs/schema-generator/customizing-schemas/generator-config#schema-generator-hooks) or by rewriting the object to expose `id` field as a function (as functions are not exposed for input objects), e.g.

```kotlin
class Widget(private val id: Int? = null, val value: String) {
   fun id(): Int = id ?: throw RuntimeException("id is required for output type")
}
