### ISSUE TITLE
Propagate ReactorContext to the coroutine context used for query processing

### ISSUE THREAD

**Issue by cldfzn** [ExpediaGroup/graphql-kotlin#934]
**Problem**:
I currently create a GraphQLContext that grabs the ReactorContext (for some tenancy features) and stores it, so I can grab it from my Query resolver to inject in to the active coroutine context. It would be nice to have this automatically propagated to the scope created for processing queries. The ReactorContext from kotlin is still experimental API, so I'm not sure  if it would be something to do just yet, but perhaps something to look at.

**Idea**:
I'm in the process of creating a FunctionDataFetcher that propagates only the reactor context, but I'd be interested in any thoughts here.

**Comment by dariuszkuc** [comment]
Hello 👋 
Even though `ReactorContext` is marked experimental, within `graphql-kotlin-spring-server` we are actually relying on this reactor-coroutine interop for propagating the GraphQL context from the webflux webfilter. Your `GraphQLContext` can then be automatically injected into the target functions.

In regards to reactor/coroutine context propagation to the target functions - unfortunately the underlying problem is that until we migrate off of `graphql-java` execution logic then we won't be able to support it generically. Currently we depend on `graphql-java` for query execution which is built on top of Java `CompletableFuture` and unfortunately doesn't have any built-in mechanism for propagating contextual data. As a result, when resolving fields we have broken parent-child coroutine relationship and no proper structured concurrency. You definitely could implement your own data fetcher/resolver that propagates the contextual information down but it will have its limitations, e.g.  given basic query

```graphql
query {
  A {
    B {
      C {
      }
    }
  }
```

if `A`, `B` and `C` resolvers are backed by functions you  could easily make a resolver that always propagate the same root context whenever resolving a field. Underlying limitation is that technically you could update context in `A` but child resolvers `B` and `C` won't know about it. If this is acceptable limitation then custom resolver approach will work.

Also see: https://github.com/ExpediaGroup/graphql-kotlin/pull/879

**Comment by cldfzn** [comment]
Hey, thanks for the response and link to the existing issue I missed!

I was looking more in to it yesterday and was noticing the issues you are mentioning with respect to the graphql-java implementation. Do you know if there has been any proposal in the graphql-java project for supporting this?

**Comment by dariuszkuc** [comment]
`graphql-java` is relying on `CompletableFuture` for queries/mutations and `Publisher` for subscriptions. Both types are from Java standard lib and AFAIK there are no plans to change the logic to start depending on any 3rd party libraries (e.g. `Reactor` or `RxJava`).

There is also an old high level proposal to split the `graphql-java` into multi-module project (https://github.com/graphql-java/graphql-java/issues/336) that could potentially simplify creation of a custom execution logic that is coroutine aware.

From `graphql-kotlin` perspective we would like to provide Kotlin native execution logic that is coroutine based and enforces structured concurrency but currently there is no ETA on this work (PRs are always welcome! :)).

**Comment by smyrick** [comment]
Since supporting this feature is not planned as commented for technical reasons, I am going to close the issue. Feel free to start any new discussions though if future questions arise

https://github.com/ExpediaGroup/graphql-kotlin/discussions
