### ISSUE TITLE
How can I configure a custom ObjectMapper to be used?

### ISSUE THREAD

**Issue by joaodias14** [ExpediaGroup/graphql-kotlin#940]
A little bit of context on this. Our default `ObjectMapper` is configured to remove non-null and non-empty values from serialized JSON. As a result, the GraphQL schema becomes invalid (because of missing definitions I guess --> https://stackoverflow.com/questions/55925747/graphql-java-error-introspection-result-missing-interfaces). 
If we remove the non-null and non-empty configurations from this default `ObjectMapper`, schema becomes valid.

A solution would be to define a specific `ObjectMapper` to be used (by `KotlinDataFetcherFactoryProvider` I guess) instead of the default one available. However, we are not being able to force the usage of such `ObjectMapper`. We have tried defining our own `SimpleKotlinDataFetcherFactoryProvider` with no luck (hoping that auto-configuration would not kick in because of `@ConditionalOnMissingBean`). How can we do this? Many thanks!

Best regards,
João Dias

**Comment by dariuszkuc** [comment]
Hello 👋 
If I understand right your issue is that you need to have two different ObjectMappers? i.e. one that strips the null/empty values from the serialized JSON (guess used for downstream calls) and another one for GraphQL?

If you are using `graphql-kotlin-spring-server` you can customize default Jackson object mapper as specified in [SpringBoot docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-the-jackson-objectmapper), e.g. by creating `Jackson2ObjectMapperBuilderCustomizer` bean with your custom logic. As for the other one (used by GraphQL), you should be able to define your own custom data fetcher factory provider bean. The default from auto-configuration library is supposed to back-off if you provide custom bean, e.g. following should work

```
@Bean
fun dataFetcherFactoryProvider(applicationContext: ApplicationContext): KotlinDataFetcherFactoryProvider {
  val objectMapper = jacksonObjectMapper()
  // customization here
  SpringKotlinDataFetcherFactoryProvider(objectMapper, applicationContext)
}
```

If the above doesn't work please provide a github project that can reproduce the issue.
