### ISSUE TITLE
Improve FunctionDataFetcher performance by caching isSubClass look ups

### ISSUE THREAD

**Issue by ameerabdul** [ExpediaGroup/graphql-kotlin#942]
**Is your feature request related to a problem? Please describe.**
Minor optimization for [FunctionDataFetcher](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt) to speed up mapping function to parameter values
- `isGraphQLContext` check in [mapParameterToValue](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt#L93) relies on [isSubClass](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt#L31) which is not as efficient and could add up when the data fetchers are called multiple times. 
- Similarly `isList` check in [convertParameterValue](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt#L108) relies on [isSubClass](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt#L27)

**Describe the solution you'd like**
* A way to cache previously looked up params so that we don't have to call `isSubClass` for already evaluated parameters.
* Similar to how PropertyDataFetcher in graphql-java handles methods and fields cache. More context this [PR](https://github.com/graphql-java/graphql-java/pull/2019)

**Describe alternatives you've considered**
* If possible construct these cached subClass look up during compile time. Not 100% sure if this is achievable. I have to do a bit more investigation

**Additional context**

**Comment by smyrick** [comment]
@ameerabdul Thank you for raising an issue and discussion. I see the code you are referring too. Anything that we put in the DataFetchers should be performant as possible as this code is executed on every operation in your server, whereas other invocations of `ifSubClass` are invoked when running the schema generator, which should be on build or start up time.

That being said, do you have some performance numbers to show how much the method is not as efficient? The Kotlin implementation is pretty straight forward since most implementations of `List` and `GraphQLContext` will only be one layer above. Is this case, storing a cache of all the classes at run time and accessing it on every request may not give us much gain and cost more in memory instead.

https://github.com/JetBrains/kotlin/blob/003ea4bcdf6d5246604cd9c187c3b314974c3cc7/core/reflection.jvm/src/kotlin/reflect/full/KClasses.kt#L231-L234

The function data fetcher can always be overridden in your code by using the `KotlinDataFetcherFactoryProvider` if you wanted to provide a custom function data fetcher that maintained its own cache

**Comment by ameerabdul** [comment]
@smyrick Thanks for the response.
Screenshots from the local profiling. These numbers are for tracing (instead of sampling), so the actual time isn't accurate. But the execution time difference between `FunctionDataFetcher` and `PropertyDataFetcher` is noticable in both screenshots.

![image](https://user-images.githubusercontent.com/51499575/100140396-80eccd80-2e56-11eb-930c-3f8b03a2a952.png)
![image](https://user-images.githubusercontent.com/51499575/100140435-8fd38000-2e56-11eb-935f-e099e8d83321.png)

> The function data fetcher can always be overridden in your code by using the KotlinDataFetcherFactoryProvider if you wanted to provide a custom function data fetcher that maintained its own cache

That is a good idea. Let me try that out in our service and see if it is giving any meaningful

**Comment by dariuszkuc** [comment]
Arbitrary `GraphQLContext` class is deprecated and will be removed in future releases. Argument conversion logic was also rewritten to no longer depend on Jackson. Original issue of caching `isSubClass` should no longer be applicable.

Feel free to reopen/open new issue if problem still persist.
